version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "pre-update-release"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:30"
      timezone: "America/New_York"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "pre-update-release"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:30"
      timezone: "America/New_York"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "pre-update-release"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:30"
      timezone: "America/New_York"
    labels:
      - "dependencies"
      - "github-actions"
