## Web UI will be available on port 5000 once deployed ##

services:
  ntp-dashboard:
    build: .
    container_name: ntp-dashboard
    network_mode: "host" # Allows container to query host's chrony/gpsd
    volumes:
      - /mnt/Apps/Storage/ntp-docker/templates/config.json:/app/config.json # Persists UI settings
    restart: unless-stopped